quote(c, "#include <geas/c/atom.h>")

typedef [int32] unsigned long pred_t;
typedef [int64] unsigned long pval_t;

quote(MLMLI, "type pred = pred_t");

typedef struct {
  [int32] unsigned long pid;
  [int64,mlname(value)] unsigned long val;
} atom;
quote(MLMLI, "type t = atom");

atom neg(atom at);
[int64] long to_int([int64] unsigned long val);
[int64,mlname(inv)] unsigned long pval_inv([int64] unsigned long val);

quote(MLI, "val at_True : atom");
quote(ML, "let at_True = { pid = Int32.zero ; value = Int64.zero }");
quote(MLI, "val at_False : atom");
quote(ML, "let at_False = neg at_True");
